//! On-chain order-book tests, run on the local Soroban host with the REAL UltraHonk verifier and the
//! REAL Poseidon tree (same as integration.rs). Fixtures in tests/fixtures/book/ are generated by
//! scripts/05_gen_book_fixtures.sh. Scenario (pair: base = asset 1, quote = asset 2):
//!   S1 SELL 100 a1 @1500 a2 (price 15), S2 SELL 100 a1 @1600 (16), S3 SELL 50 a1 @1000 (20),
//!   B1 BUY offer 2400 a2 want 100 a1 (price 24). All input notes shielded at leaves 0..3 (root R4).
//! B1 crosses S1 (full) then S2 (partial 56), rests with 4 a2; S3 untouched. Then we cancel S2 and
//! prune the (expired) S3.

use settlement::{
    AssetInit, AssetKind, DataKey, Error, OrderEntry, PairDef, Settlement, SettlementClient,
};
use soroban_sdk::{
    testutils::{storage::Persistent as _, Address as _, Events, Ledger},
    token::StellarAssetClient,
    vec,
    xdr::{ContractEventBody, Int128Parts, ScVal},
    Address, Bytes, BytesN, Env, Vec,
};

const VK: &[u8] = include_bytes!("fixtures/book/vk");
const CANCEL_VK: &[u8] = include_bytes!("fixtures/book/cancel_vk");
const CANCEL_PROOF: &[u8] = include_bytes!("fixtures/book/cancel_proof");
const CANCEL_PI: &[u8] = include_bytes!("fixtures/book/cancel_public_inputs");

const P_S1: &[u8] = include_bytes!("fixtures/book/proof_s1");
const PI_S1: &[u8] = include_bytes!("fixtures/book/public_inputs_s1");
const P_S2: &[u8] = include_bytes!("fixtures/book/proof_s2");
const PI_S2: &[u8] = include_bytes!("fixtures/book/public_inputs_s2");
const P_S3: &[u8] = include_bytes!("fixtures/book/proof_s3");
const PI_S3: &[u8] = include_bytes!("fixtures/book/public_inputs_s3");
const P_B1: &[u8] = include_bytes!("fixtures/book/proof_b1");
const PI_B1: &[u8] = include_bytes!("fixtures/book/public_inputs_b1");

const OT_S1: &[u8] = include_bytes!("fixtures/book/owner_tag_s1");
const OT_S2: &[u8] = include_bytes!("fixtures/book/owner_tag_s2");
const OT_B1: &[u8] = include_bytes!("fixtures/book/owner_tag_b1");
const OT_S3: &[u8] = include_bytes!("fixtures/book/owner_tag_s3");

const A1: u32 = 1; // base
const A2: u32 = 2; // quote
const SIDE_BUY: u32 = 0;
const SIDE_SELL: u32 = 1;

fn test_env() -> Env {
    let env = Env::default();
    env.ledger().set_protocol_version(26);
    env.ledger().set_timestamp(1000); // before every fixture's expiry
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();
    env
}

fn deploy(env: &Env, assets: Vec<AssetInit>, pairs: Vec<PairDef>) -> Address {
    let admin = Address::generate(env);
    env.register(
        Settlement,
        (
            bytes(env, VK),
            bytes(env, VK),
            bytes(env, CANCEL_VK),
            bytes(env, VK),
            admin,
            assets,
            pairs,
        ),
    )
}

fn bytes(env: &Env, b: &[u8]) -> Bytes {
    Bytes::from_slice(env, b)
}
fn tag(env: &Env, b: &[u8]) -> BytesN<32> {
    BytesN::from_array(env, &b.try_into().unwrap())
}

/// Create a SAC for `asset_id`, mint `amount` to a fresh holder, and return the constructor entry
/// (`Dual`) plus the holder. Pass the `AssetInit` to `deploy` (assets are constructor-only now).
fn fund(env: &Env, asset_id: u32, amount: i128) -> (AssetInit, Address) {
    let sac = env.register_stellar_asset_contract_v2(Address::generate(env));
    let holder = Address::generate(env);
    StellarAssetClient::new(env, &sac.address()).mint(&holder, &amount);
    (
        AssetInit { asset_id, token: Some(sac.address()), kind: AssetKind::Dual },
        holder,
    )
}

/// The two funded assets used by the book scenario, as constructor `AssetInit`s plus their holders.
fn book_assets(env: &Env) -> (Vec<AssetInit>, Address, Address) {
    let (a1, h1) = fund(env, A1, 250); // S1(100) + S2(100) + S3(50)
    let (a2, h2) = fund(env, A2, 2400); // B1(2400)
    (vec![env, a1, a2], h1, h2)
}

/// Shield the four input notes in the fixture order (leaves 0..3) so the tree reaches R4, the root
/// the four order proofs were generated against.
fn shield_book_notes(env: &Env, id: &Address, h1: &Address, h2: &Address) {
    let client = SettlementClient::new(env, id);
    client.shield(h1, &A1, &100, &tag(env, OT_S1));
    client.shield(h1, &A1, &100, &tag(env, OT_S2));
    client.shield(h2, &A2, &2400, &tag(env, OT_B1));
    client.shield(h1, &A1, &50, &tag(env, OT_S3));
}

/// Deploy with the book's two assets + canonical pair (id 0), shield the four notes, return the id.
fn setup_book(env: &Env) -> Address {
    let (assets, h1, h2) = book_assets(env);
    let id = deploy(env, assets, vec![env, PairDef { base_asset: A1, quote_asset: A2 }]);
    shield_book_notes(env, &id, &h1, &h2);
    id
}

#[test]
fn book_lifecycle_rest_partial_fill_cancel_prune() {
    let env = test_env();
    let id = setup_book(&env);
    let client = SettlementClient::new(&env, &id);

    // Three sells rest (book empty -> no cross), price-sorted ascending S1(15), S2(16), S3(20).
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));
    client.submit_order(&bytes(&env, P_S3), &bytes(&env, PI_S3));
    assert_eq!(client.book_sequence(), 3, "one upsert per resting order");
    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 3, "three resting sells");
    assert_eq!(sells.get(0).unwrap().min_out, 1500, "best ask (lowest price) first");
    assert_eq!(sells.get(1).unwrap().min_out, 1600);
    assert_eq!(sells.get(2).unwrap().min_out, 1000); // S3, price 20 (1000/50), last
    assert!(client.book(&0, &SIDE_BUY).is_empty());

    // The buy taker crosses: fills S1 fully (100 a1 / 1500 a2), then S2 partially (56 a1 / 896 a2),
    // then cannot afford another lot (4 a2 left) -> rests on the buy side. S3 is never reached.
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    assert_eq!(client.book_sequence(), 6, "remove S1 + update S2 + rest B1");

    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 2, "S1 fully consumed and removed");
    let s2 = sells.get(0).unwrap();
    assert_eq!(s2.order_id.to_array(), pi_word_nf(PI_S2));
    assert_eq!(s2.min_out, 1600, "S2 is now best ask");
    assert_eq!(s2.remaining_in, 44, "S2: 100 - 56 filled = 44 a1 still locked");
    let s3 = sells.get(1).unwrap();
    assert_eq!(s3.remaining_in, 50, "S3 untouched");

    let buys = client.book(&0, &SIDE_BUY);
    assert_eq!(buys.len(), 1, "taker remainder rests");
    assert_eq!(buys.get(0).unwrap().remaining_in, 4, "B1: 2400 - 1500 - 896 = 4 a2 left");

    // Conservation: nothing created or destroyed.
    //   a1 shielded 250 = minted(100 to taker + 56 to taker) 156 + locked(S2 44 + S3 50) 94 + buy-side a1 0
    //   a2 shielded 2400 = minted(1500 to S1 + 896 to S2) 2396 + locked(B1 4)
    // (locked amounts are the remaining_in above; minted amounts are asserted via the lot math.)
    assert_eq!(156 + 44 + 50, 250, "a1 conserved");
    assert_eq!(2396 + 4, 2400, "a2 conserved");

    // Cancel S2: returns its 44 a1 of remaining locked funds and removes the entry.
    client.cancel_order(&0, &SIDE_SELL, &bytes(&env, CANCEL_PROOF), &bytes(&env, CANCEL_PI));
    assert_eq!(client.book_sequence(), 7, "cancel emits one removal");
    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 1, "S2 cancelled");
    assert_eq!(sells.get(0).unwrap().remaining_in, 50, "only S3 remains");

    // A second identical cancel finds no entry (removal is the single-use guard).
    let err = env
        .as_contract(&id, || {
            Settlement::cancel_order(
                env.clone(),
                0,
                SIDE_SELL,
                bytes(&env, CANCEL_PROOF),
                bytes(&env, CANCEL_PI),
            )
        })
        .expect_err("replayed cancel");
    assert_eq!(err as u32, Error::OrderNotFound as u32);

    // S3 expires at t=5000; advance past it and prune permissionlessly.
    env.ledger().set_timestamp(6000);
    let removed = client.prune_expired(&0, &SIDE_SELL, &10);
    assert_eq!(client.book_sequence(), 8, "prune emits one removal");
    assert_eq!(removed, 1, "S3 pruned");
    assert!(client.book(&0, &SIDE_SELL).is_empty(), "sell book empty after prune");
}

/// Decode the data payload of every `filled` event currently in the env. Returns
/// `(asset_in, amount_in, asset_out, amount_out)` tuples (taker-perspective; the owner tag is the
/// 5th field but not needed here).
fn filled_events(env: &Env) -> std::vec::Vec<(u32, i128, u32, i128)> {
    let i128_of = |p: &Int128Parts| ((p.hi as i128) << 64) | (p.lo as i128);
    env.events()
        .all()
        .events()
        .iter()
        .filter_map(|e| {
            let ContractEventBody::V0(v0) = &e.body;
            match v0.topics.first() {
                Some(ScVal::Symbol(s)) if s.to_string() == "filled" => match v0.data.clone() {
                    ScVal::Vec(Some(v)) => match (&v[0], &v[1], &v[2], &v[3]) {
                        (ScVal::U32(ai), ScVal::I128(amt_in), ScVal::U32(ao), ScVal::I128(amt_out)) => {
                            Some((*ai, i128_of(amt_in), *ao, i128_of(amt_out)))
                        }
                        _ => None,
                    },
                    _ => None,
                },
                _ => None,
            }
        })
        .collect()
}

#[test]
fn crossing_order_emits_filled_event_with_amounts_and_currencies() {
    let env = test_env();
    let id = setup_book(&env);
    let client = SettlementClient::new(&env, &id);

    // Three sells rest (book empty -> no cross): no `filled` event for resting orders.
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));
    client.submit_order(&bytes(&env, P_S3), &bytes(&env, PI_S3));
    assert!(filled_events(&env).is_empty(), "resting orders emit no `filled` event");

    // The buy taker crosses S1 (full) + S2 (partial): exactly one taker-perspective summary.
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    let filled = filled_events(&env);
    assert_eq!(filled.len(), 1, "one `filled` event from the crossing taker");
    // BUY spends quote (a2) to receive base (a1): in 1500+896=2396 a2, out 100+56=156 a1.
    assert_eq!(filled[0], (A2, 2396, A1, 156), "filled summary: asset_in/amount_in/asset_out/amount_out");
}

#[test]
fn submit_order_fits_cpu_budget() {
    // Worst-ish case for one submit: verify (~80M) + two fills (4 proceeds inserts). Local-host
    // metering under-counts vs on-chain, so this is a regression guard, not the on-chain figure.
    let env = test_env();
    let id = setup_book(&env);
    let client = SettlementClient::new(&env, &id);
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));

    env.cost_estimate().budget().reset_unlimited();
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    let cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("submit_order (verify + 2 fills, 4 inserts) CPU (local host): {cpu}");
    assert!(cpu < 400_000_000, "submit_order CPU {cpu} exceeds the 400M budget");
}

/// 32-byte big-endian field word for a small integer tag (matches how the fixtures encode the
/// literal output_owner_tag values like 9011).
fn tag_word(n: u32) -> [u8; 32] {
    let mut w = [0u8; 32];
    w[28..32].copy_from_slice(&n.to_be_bytes());
    w
}

#[test]
fn indexer_reproduces_book_root_after_fills() {
    use mosaic_indexer::{u256_to_word, NoteTree};

    let env = test_env();
    let id = setup_book(&env);
    let client = SettlementClient::new(&env, &id);
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));
    client.submit_order(&bytes(&env, P_S3), &bytes(&env, PI_S3));
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    let onchain_root = client.root().to_array();

    // Rebuild the tree off-chain: the four shields, then the book's `noteins` mints in emission
    // order. Fill of S1 mints (a1,100 -> B1 tag 9011) then (a2,1500 -> S1 tag 9001); fill of S2 mints
    // (a1,56 -> 9011) then (a2,896 -> S2 tag 9006). output_owner_tags are the fixtures' literals.
    let mut tree = NoteTree::new(&env);
    tree.ingest_shielded(A1, 100, OT_S1.try_into().unwrap());
    tree.ingest_shielded(A1, 100, OT_S2.try_into().unwrap());
    tree.ingest_shielded(A2, 2400, OT_B1.try_into().unwrap());
    tree.ingest_shielded(A1, 50, OT_S3.try_into().unwrap());
    tree.ingest_note(A1, 100, &tag_word(9011));
    tree.ingest_note(A2, 1500, &tag_word(9001));
    tree.ingest_note(A1, 56, &tag_word(9011));
    tree.ingest_note(A2, 896, &tag_word(9006));

    assert_eq!(
        u256_to_word(&tree.root()),
        onchain_root,
        "indexer root (shields + noteins replay) must equal the on-chain root"
    );
    // A proceeds note's reconstructed path folds to the root, so its owner could later unshield it.
    let leaf = tree.leaf(5).unwrap(); // S1 maker's 1500 a2 proceeds
    let p = tree.path(5);
    assert_eq!(u256_to_word(&tree.circuit_fold(&leaf, &p)), onchain_root);
}

#[test]
fn submit_order_cost_vs_book_depth() {
    // How does submit_order cost scale with book DEPTH? With the v1 monolithic Vec<OrderEntry>, each
    // submit deserializes + reserializes the whole opposing side. We measure two full-64-deep cases
    // against the 2-entry baseline (~185M local): (a) depth only — non-crossing asks, B1 reads 64 and
    // rests; (b) the true worst case — full book AND the 4-fill cap, B1 crosses 64 small asks, fills
    // MAX_FILLS_PER_SUBMIT, then rests. Synthetic entries (plaintext book data; no proofs needed).
    use soroban_sdk::Vec as SVec;

    fn fill_sell_book(env: &Env, id: &Address, amount_in: i128, min_out: i128) {
        env.as_contract(id, || {
            let mut v: SVec<OrderEntry> = SVec::new(env);
            for n in 0..64u32 {
                v.push_back(OrderEntry {
                    order_id: BytesN::from_array(env, &tag_word(30000 + n)),
                    amount_in,
                    min_out,
                    remaining_in: amount_in,
                    output_owner_tag: BytesN::from_array(env, &tag_word(40000 + n)),
                    cancel_owner_tag: BytesN::from_array(env, &tag_word(50000 + n)),
                    order_leaf: BytesN::from_array(env, &tag_word(60000 + n)),
                    expiry: 9999999999,
                    partial_allowed: true,
                });
            }
            env.storage().persistent().set(&DataKey::Book(0, SIDE_SELL), &v);
        });
    }

    // (a) depth only: 64 non-crossing asks priced at 25 (> B1's limit of 24).
    {
        let env = test_env();
        let id = setup_book(&env);
        fill_sell_book(&env, &id, 100, 2500);
        env.cost_estimate().budget().reset_unlimited();
        SettlementClient::new(&env, &id).submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
        let cpu = env.cost_estimate().budget().cpu_instruction_cost();
        std::println!("submit_order: FULL 64 book, NO cross (depth only) CPU (local): {cpu}");
        assert!(cpu < 400_000_000);
    }

    // (b) worst case: 64 small crossing asks (10 a1 @150, price 15) -> B1 fills the MAX_FILLS cap, rests.
    let env = test_env();
    let id = setup_book(&env);
    fill_sell_book(&env, &id, 10, 150);
    let client = SettlementClient::new(&env, &id);
    env.cost_estimate().budget().reset_unlimited();
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    let cpu = env.cost_estimate().budget().cpu_instruction_cost();
    let sells_left = client.book(&0, &SIDE_SELL).len();
    std::println!(
        "submit_order: FULL 64 book + MAX_FILLS cap (WORST CASE) CPU (local): {cpu}; sells left {sells_left}"
    );
    assert_eq!(sells_left, 60, "4 of 64 asks consumed (MAX_FILLS_PER_SUBMIT)");
    assert!(cpu < 400_000_000, "worst-case submit CPU {cpu} exceeds 400M");
}

#[test]
fn critical_state_ttl_is_extended_and_kept_alive() {
    // Fund-critical persistent state must be bumped to the network max TTL on write, and the
    // permissionless keep_alive heartbeat must re-extend it after ledgers pass — so nothing archives
    // in practice (and even if it did, persistent entries are restorable, never lost).
    let env = test_env();
    let id = setup_book(&env);
    let client = SettlementClient::new(&env, &id);
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1)); // writes Book + nullifier

    let max = env.as_contract(&id, || env.storage().max_ttl());
    let crit = [
        DataKey::TreeRoot,
        DataKey::TreeNext,
        DataKey::TreeFilled,
        DataKey::PairCount,
        DataKey::Pair(0),
        DataKey::Book(0, SIDE_SELL),
    ];

    // (1) On write, every critical entry is at (essentially) max TTL.
    env.as_contract(&id, || {
        for k in crit.iter() {
            let ttl = env.storage().persistent().get_ttl(k);
            assert!(ttl >= max - 16, "fresh TTL {ttl} not ~max {max}");
        }
    });

    // (2) Let many ledgers pass: TTL decays but the entry is still live.
    let elapsed = 100_000u32;
    env.ledger().set_sequence_number(env.ledger().sequence() + elapsed);
    env.as_contract(&id, || {
        let ttl = env.storage().persistent().get_ttl(&DataKey::TreeRoot);
        assert!(ttl < max && ttl > 0, "TTL {ttl} should have decayed but stayed live");
    });

    // (3) keep_alive re-extends everything structural back to max.
    client.keep_alive();
    env.as_contract(&id, || {
        for k in crit.iter() {
            let ttl = env.storage().persistent().get_ttl(k);
            assert!(ttl >= max - 16, "after keep_alive TTL {ttl} not back to ~max {max}");
        }
    });

    // (4) keep_alive_keys re-extends a specific nullifier + root (the unbounded sets).
    let onchain_root = client.root();
    env.ledger().set_sequence_number(env.ledger().sequence() + elapsed);
    let nf = BytesN::from_array(&env, &pi_word_nf(PI_S1));
    let mut nfs = soroban_sdk::Vec::new(&env);
    nfs.push_back(nf.clone());
    let mut roots = soroban_sdk::Vec::new(&env);
    roots.push_back(onchain_root.clone());
    client.keep_alive_keys(&nfs, &roots);
    env.as_contract(&id, || {
        assert!(env.storage().persistent().get_ttl(&DataKey::Nullifier(nf)) >= max - 16);
        assert!(env.storage().persistent().get_ttl(&DataKey::Root(onchain_root)) >= max - 16);
    });
}

/// The nullifier (public input field [2]) of an order proof, as a 32-byte word.
fn pi_word_nf(pi: &[u8]) -> [u8; 32] {
    pi[2 * 32..3 * 32].try_into().unwrap()
}

#[test]
fn submit_rejects_expired_order() {
    // Same shields (so S3's proof root R4 is published), but the ledger is already past S3's expiry.
    let env = test_env();
    let id = setup_book(&env);
    env.ledger().set_timestamp(6000); // > S3 expiry (5000)

    let err = env
        .as_contract(&id, || {
            Settlement::submit_order(env.clone(), bytes(&env, P_S3), bytes(&env, PI_S3))
        })
        .expect_err("expired order");
    assert_eq!(err as u32, Error::OrderExpired as u32);
}

#[test]
fn submit_rejects_unregistered_pair() {
    // Shield the notes but never register the pair (deploy with assets only, no pairs).
    let env = test_env();
    let (assets, h1, h2) = book_assets(&env);
    let id = deploy(&env, assets, Vec::new(&env));
    shield_book_notes(&env, &id, &h1, &h2);

    let err = env
        .as_contract(&id, || {
            Settlement::submit_order(env.clone(), bytes(&env, P_S1), bytes(&env, PI_S1))
        })
        .expect_err("pair not registered");
    assert_eq!(err as u32, Error::PairNotRegistered as u32);
}
