//! On-chain order-book tests, run on the local Soroban host with the REAL UltraHonk verifier and the
//! REAL Poseidon tree (same as integration.rs). Fixtures in tests/fixtures/book/ are generated by
//! scripts/05_gen_book_fixtures.sh. Scenario (pair: base = asset 1, quote = asset 2):
//!   S1 SELL 100 a1 @1500 a2 (price 15), S2 SELL 100 a1 @1600 (16), S3 SELL 50 a1 @1000 (20),
//!   B1 BUY offer 2400 a2 want 100 a1 (price 24). All input notes shielded at leaves 0..3 (root R4).
//! B1 crosses S1 (full) then S2 (partial 56), rests with 4 a2; S3 untouched. Then we cancel S2 and
//! prune the (expired) S3.

use settlement::{Error, Settlement, SettlementClient};
use soroban_sdk::{
    testutils::{Address as _, Ledger},
    token::StellarAssetClient,
    Address, Bytes, BytesN, Env,
};

const VK: &[u8] = include_bytes!("fixtures/book/vk");
const CANCEL_VK: &[u8] = include_bytes!("fixtures/book/cancel_vk");
const CANCEL_PROOF: &[u8] = include_bytes!("fixtures/book/cancel_proof");
const CANCEL_PI: &[u8] = include_bytes!("fixtures/book/cancel_public_inputs");

const P_S1: &[u8] = include_bytes!("fixtures/book/proof_s1");
const PI_S1: &[u8] = include_bytes!("fixtures/book/public_inputs_s1");
const P_S2: &[u8] = include_bytes!("fixtures/book/proof_s2");
const PI_S2: &[u8] = include_bytes!("fixtures/book/public_inputs_s2");
const P_S3: &[u8] = include_bytes!("fixtures/book/proof_s3");
const PI_S3: &[u8] = include_bytes!("fixtures/book/public_inputs_s3");
const P_B1: &[u8] = include_bytes!("fixtures/book/proof_b1");
const PI_B1: &[u8] = include_bytes!("fixtures/book/public_inputs_b1");

const OT_S1: &[u8] = include_bytes!("fixtures/book/owner_tag_s1");
const OT_S2: &[u8] = include_bytes!("fixtures/book/owner_tag_s2");
const OT_B1: &[u8] = include_bytes!("fixtures/book/owner_tag_b1");
const OT_S3: &[u8] = include_bytes!("fixtures/book/owner_tag_s3");

const A1: u32 = 1; // base
const A2: u32 = 2; // quote
const CANCEL_OP: u32 = 3;
const SIDE_BUY: u32 = 0;
const SIDE_SELL: u32 = 1;

fn test_env() -> Env {
    let env = Env::default();
    env.ledger().set_protocol_version(26);
    env.ledger().set_timestamp(1000); // before every fixture's expiry
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();
    env
}

fn deploy(env: &Env) -> Address {
    let admin = Address::generate(env);
    env.register(Settlement, (Bytes::from_slice(env, VK), admin))
}

fn bytes(env: &Env, b: &[u8]) -> Bytes {
    Bytes::from_slice(env, b)
}
fn tag(env: &Env, b: &[u8]) -> BytesN<32> {
    BytesN::from_array(env, &b.try_into().unwrap())
}

/// Register a SAC for `asset_id`, mint `amount` to a fresh holder, register it, return the holder.
fn fund(env: &Env, id: &Address, asset_id: u32, amount: i128) -> Address {
    let sac = env.register_stellar_asset_contract_v2(Address::generate(env));
    let holder = Address::generate(env);
    StellarAssetClient::new(env, &sac.address()).mint(&holder, &amount);
    SettlementClient::new(env, id).register_asset(&asset_id, &sac.address());
    holder
}

/// Shield the four input notes in the fixture order (leaves 0..3) so the tree reaches R4, the root
/// the four order proofs were generated against; register the canonical pair (id 0).
fn setup_book(env: &Env, id: &Address) {
    let client = SettlementClient::new(env, id);
    let h1 = fund(env, id, A1, 250); // S1(100) + S2(100) + S3(50)
    let h2 = fund(env, id, A2, 2400); // B1(2400)
    client.shield(&h1, &A1, &100, &tag(env, OT_S1));
    client.shield(&h1, &A1, &100, &tag(env, OT_S2));
    client.shield(&h2, &A2, &2400, &tag(env, OT_B1));
    client.shield(&h1, &A1, &50, &tag(env, OT_S3));
    client.register_pair(&A1, &A2);
}

#[test]
fn book_lifecycle_rest_partial_fill_cancel_prune() {
    let env = test_env();
    let id = deploy(&env);
    let client = SettlementClient::new(&env, &id);
    setup_book(&env, &id);
    client.set_vk(&CANCEL_OP, &bytes(&env, CANCEL_VK));

    // Three sells rest (book empty -> no cross), price-sorted ascending S1(15), S2(16), S3(20).
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));
    client.submit_order(&bytes(&env, P_S3), &bytes(&env, PI_S3));
    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 3, "three resting sells");
    assert_eq!(sells.get(0).unwrap().min_out, 1500, "best ask (lowest price) first");
    assert_eq!(sells.get(1).unwrap().min_out, 1600);
    assert_eq!(sells.get(2).unwrap().min_out, 1000); // S3, price 20 (1000/50), last
    assert!(client.book(&0, &SIDE_BUY).is_empty());

    // The buy taker crosses: fills S1 fully (100 a1 / 1500 a2), then S2 partially (56 a1 / 896 a2),
    // then cannot afford another lot (4 a2 left) -> rests on the buy side. S3 is never reached.
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));

    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 2, "S1 fully consumed and removed");
    let s2 = sells.get(0).unwrap();
    assert_eq!(s2.min_out, 1600, "S2 is now best ask");
    assert_eq!(s2.remaining_in, 44, "S2: 100 - 56 filled = 44 a1 still locked");
    let s3 = sells.get(1).unwrap();
    assert_eq!(s3.remaining_in, 50, "S3 untouched");

    let buys = client.book(&0, &SIDE_BUY);
    assert_eq!(buys.len(), 1, "taker remainder rests");
    assert_eq!(buys.get(0).unwrap().remaining_in, 4, "B1: 2400 - 1500 - 896 = 4 a2 left");

    // Conservation: nothing created or destroyed.
    //   a1 shielded 250 = minted(100 to taker + 56 to taker) 156 + locked(S2 44 + S3 50) 94 + buy-side a1 0
    //   a2 shielded 2400 = minted(1500 to S1 + 896 to S2) 2396 + locked(B1 4)
    // (locked amounts are the remaining_in above; minted amounts are asserted via the lot math.)
    assert_eq!(156 + 44 + 50, 250, "a1 conserved");
    assert_eq!(2396 + 4, 2400, "a2 conserved");

    // Cancel S2: returns its 44 a1 of remaining locked funds and removes the entry.
    client.cancel_order(&0, &SIDE_SELL, &bytes(&env, CANCEL_PROOF), &bytes(&env, CANCEL_PI));
    let sells = client.book(&0, &SIDE_SELL);
    assert_eq!(sells.len(), 1, "S2 cancelled");
    assert_eq!(sells.get(0).unwrap().remaining_in, 50, "only S3 remains");

    // A second identical cancel finds no entry (removal is the single-use guard).
    let err = env
        .as_contract(&id, || {
            Settlement::cancel_order(
                env.clone(),
                0,
                SIDE_SELL,
                bytes(&env, CANCEL_PROOF),
                bytes(&env, CANCEL_PI),
            )
        })
        .expect_err("replayed cancel");
    assert_eq!(err as u32, Error::OrderNotFound as u32);

    // S3 expires at t=5000; advance past it and prune permissionlessly.
    env.ledger().set_timestamp(6000);
    let removed = client.prune_expired(&0, &SIDE_SELL, &10);
    assert_eq!(removed, 1, "S3 pruned");
    assert!(client.book(&0, &SIDE_SELL).is_empty(), "sell book empty after prune");
}

#[test]
fn submit_order_fits_cpu_budget() {
    // Worst-ish case for one submit: verify (~80M) + two fills (4 proceeds inserts). Local-host
    // metering under-counts vs on-chain, so this is a regression guard, not the on-chain figure.
    let env = test_env();
    let id = deploy(&env);
    let client = SettlementClient::new(&env, &id);
    setup_book(&env, &id);
    client.submit_order(&bytes(&env, P_S1), &bytes(&env, PI_S1));
    client.submit_order(&bytes(&env, P_S2), &bytes(&env, PI_S2));

    env.cost_estimate().budget().reset_unlimited();
    client.submit_order(&bytes(&env, P_B1), &bytes(&env, PI_B1));
    let cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("submit_order (verify + 2 fills, 4 inserts) CPU (local host): {cpu}");
    assert!(cpu < 400_000_000, "submit_order CPU {cpu} exceeds the 400M budget");
}

#[test]
fn submit_rejects_expired_order() {
    // Same shields (so S3's proof root R4 is published), but the ledger is already past S3's expiry.
    let env = test_env();
    let id = deploy(&env);
    setup_book(&env, &id);
    env.ledger().set_timestamp(6000); // > S3 expiry (5000)

    let err = env
        .as_contract(&id, || {
            Settlement::submit_order(env.clone(), bytes(&env, P_S3), bytes(&env, PI_S3))
        })
        .expect_err("expired order");
    assert_eq!(err as u32, Error::OrderExpired as u32);
}

#[test]
fn submit_rejects_unregistered_pair() {
    // Shield the notes but never register the pair.
    let env = test_env();
    let id = deploy(&env);
    let client = SettlementClient::new(&env, &id);
    let h1 = fund(&env, &id, A1, 250);
    let h2 = fund(&env, &id, A2, 2400);
    client.shield(&h1, &A1, &100, &tag(&env, OT_S1));
    client.shield(&h1, &A1, &100, &tag(&env, OT_S2));
    client.shield(&h2, &A2, &2400, &tag(&env, OT_B1));
    client.shield(&h1, &A1, &50, &tag(&env, OT_S3));

    let err = env
        .as_contract(&id, || {
            Settlement::submit_order(env.clone(), bytes(&env, P_S1), bytes(&env, PI_S1))
        })
        .expect_err("pair not registered");
    assert_eq!(err as u32, Error::PairNotRegistered as u32);
}
